name: Java CI G7

on:	
  push:	
    branches: [ main ]	

jobs:	
  build:	

    runs-on: ubuntu-latest	

    steps:	
    - uses: actions/checkout@v2	
    - name: Set up JDK 11	
      uses: actions/setup-java@v2	
      with:	
        java-version: '11'	
        distribution: 'temurin'	
        cache: maven	
    - name: Deploy  	
      run: mvn -B package --file pom.xml
    - name: Upload application	
      uses: appleboy/scp-action@master	
      with:       	
        host: drobles.cl       	
        username: ec2-user     	
        password: grupo7	
        port: 22	
        source: "/home/runner/work/ms-iclab/ms-iclab/target/DevOpsUsach2020-2.3.4.RELEASE.jar"      	
        target: "/home/ec2-user/"	
    - name: test2  	
      run: echo end
