name: Java CI G7

on:	
  push:	
    branches: [ main ]	

jobs:	
  build:	

    runs-on: ubuntu-latest	

    steps:	
    - uses: actions/checkout@v2	
    - name: Set up JDK 11	
      uses: actions/setup-java@v2	
      with:	
        java-version: '11'	
        distribution: 'temurin'	
        cache: maven	
    - name: Deploy  	
      run: mvn -B package --file pom.xml
    - name: Upload application	
      uses: appleboy/scp-action@master	
      with:       	
        host: drobles.cl       	
        username: ec2-user     	
        password: grupo7	
        port: 22	
        source: "/home/runner/work/ms-iclab/ms-iclab/build/DevOpsUsach2020-0.0.1.jar"      	
        target: "/home/ec2-user/"	
    - name: test2  	
      run: echo end
    - name: Start Service	DevOpsUsach2020
      uses: appleboy/ssh-action@master	
      with:	
        host: drobles.cl         	
        username: ec2-user     	
        password: grupo7
        port: 22	
        script: |	
          sudo /etc/init.d/devops stop	|| true
          mv /home/ec2-user/devops.jar /home/ec2-user/devops-old.jar || true	
          mv /home/ec2-user/github/workspace/build/DevOpsUsach2020-0.0.1.jar /home/ec2-user/devops.jar
          sudo rm -rf /etc/init.d/devops || true	
          sudo ln -s /home/ec2-user/devops.jar /etc/init.d/devops	
          /etc/init.d/devops start	
